### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jon-dominguez94** [jon-dominguez94/chill-flix#1]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

**Comment by jenvomo** [comment]
![screen shot 2018-12-14 at 3 53 34 pm](https://user-images.githubusercontent.com/39272166/50035792-e96b7880-ffb8-11e8-92fe-064e6bf9995e.png)
![screen shot 2018-12-14 at 3 53 53 pm](https://user-images.githubusercontent.com/39272166/50035795-ed979600-ffb8-11e8-8e04-292f7e1bbc64.png)
- [x] Placeholder on the inputs instead of the small text up top.  Unless you want to do the css transition, you definitely could
- [x] Background color of the input boxes

**Comment by jenvomo** [comment]
Netflix:
![screen shot 2018-12-17 at 9 13 03 am](https://user-images.githubusercontent.com/39272166/50103219-0207a880-01dc-11e9-9e3e-c10a046ea6f6.png)
Chillflix:
![screen shot 2018-12-17 at 9 12 52 am](https://user-images.githubusercontent.com/39272166/50103204-fae09a80-01db-11e9-8ea9-44d696ac3e0a.png)

- [x] Increase padding around placeholder
- [x] Decrease font size of placeholder

Awesome job on the transition of the placeholder to the small text above! Home page is looking amazing as well.  Keep it up!
